### ISSUE TITLE
Error in ruuning code

### ISSUE THREAD

**Issue by ketsu1234** [acht7111020/ADLxMLDS2017#1]
Sir can you please provide a file showing process of running code of video captioning if possible.

**Comment by tatajack** [comment]
@ketsu1234 IMHO the code provided should run with no error
could you kindly provide some description about your error?

**Comment by ketsu1234** [comment]
> @ketsu1234 IMHO the code provided should run with no error
> could you kindly provide some description about your error?

Actually there is no error but the code is not showing any output so can you please provide guidance about how to run this code.

**Comment by acht7111020** [comment]
I've modified my readme.md file in video captioning project. You could follow the steps to run the code.  
Because this was my assignment of a course, I think it's not appropriate to upload the whole files (including pre-processing files) to github. Sorry for any inconvenience.
